insert into public.curriculum_topics(crdp_grade,subject,unit,chapter,topic,learning_objective,source_url,source_version,source_page,mapping_status)
values
('Basic Education Grade 9','Mathematics','Numbers','9','Real numbers','Classify rational and irrational numbers; rationalize denominators; calculate with and represent real numbers on a number line.','https://www.crdp.org/sites/default/files/inline-files/14-Math_2025-2026_.pdf','CRDP curriculum topics 2025–2026',34,'verified'),
('Basic Education Grade 9','Mathematics','Algebra','11','Polynomials','Identify polynomial objects; operate on polynomials; evaluate polynomials and find roots; work with fractional algebraic expressions and equations.','https://www.crdp.org/sites/default/files/inline-files/14-Math_2025-2026_.pdf','CRDP curriculum topics 2025–2026',34,'verified'),
('Basic Education Grade 9','Mathematics','Trigonometry','12','Trigonometric relations','Use sine, cosine and tangent of an acute angle in a right triangle and connect tangent with a line in a coordinate plane.','https://www.crdp.org/sites/default/files/inline-files/14-Math_2025-2026_.pdf','CRDP curriculum topics 2025–2026',34,'verified'),
('Basic Education Grade 9','Mathematics','Analytic geometry','13','The line in the plane','Find a line equation from a point and slope; calculate segment length in a coordinate plane.','https://www.crdp.org/sites/default/files/inline-files/14-Math_2025-2026_.pdf','CRDP curriculum topics 2025–2026',34,'verified'),
('Basic Education Grade 9','Mathematics','Statistics','14','Statistical records','Present data numerically and graphically; calculate the mean of a statistical series.','https://www.crdp.org/sites/default/files/inline-files/14-Math_2025-2026_.pdf','CRDP curriculum topics 2025–2026',35,'verified'),
('First Secondary','Mathematics','Statistics and probability','1','Statistical vocabulary','Identify populations, individuals, characteristics and frequencies.','https://www.crdp.org/sites/default/files/inline-files/14-Math_2025-2026_.pdf','CRDP curriculum topics 2025–2026',36,'verified'),
('First Secondary','Mathematics','Statistics and probability','2','Graphical representation of a statistical distribution','Interpret cumulative counts and represent statistical variables.','https://www.crdp.org/sites/default/files/inline-files/14-Math_2025-2026_.pdf','CRDP curriculum topics 2025–2026',36,'verified'),
('First Secondary','Mathematics','Statistics and probability','3','Statistical indicators','Study statistical series and measures of position and dispersion.','https://www.crdp.org/sites/default/files/inline-files/14-Math_2025-2026_.pdf','CRDP curriculum topics 2025–2026',36,'verified'),
('First Secondary','Mathematics','Algebra','4','Sets','Work with sets, subsets, set operations and number sets.','https://www.crdp.org/sites/default/files/inline-files/14-Math_2025-2026_.pdf','CRDP curriculum topics 2025–2026',36,'verified'),
('First Secondary','Mathematics','Algebra','5','Powers of a real number','Work with integer powers, square roots, nth roots, rational powers and real powers of positive real numbers.','https://www.crdp.org/sites/default/files/inline-files/14-Math_2025-2026_.pdf','CRDP curriculum topics 2025–2026',37,'verified'),
('First Secondary','Mathematics','Algebra','6','Order on real numbers','Operate with inequalities, bound real numbers and use intervals.','https://www.crdp.org/sites/default/files/inline-files/14-Math_2025-2026_.pdf','CRDP curriculum topics 2025–2026',37,'verified'),
('First Secondary','Mathematics','Algebra','7','Absolute value and approximation','Use absolute value of a real number and centered intervals.','https://www.crdp.org/sites/default/files/inline-files/14-Math_2025-2026_.pdf','CRDP curriculum topics 2025–2026',37,'verified'),
('First Secondary','Mathematics','Trigonometry','8','Trigonometric lines','Use degrees and radians, locate points and work with trigonometric lines.','https://www.crdp.org/sites/default/files/inline-files/14-Math_2025-2026_.pdf','CRDP curriculum topics 2025–2026',37,'verified'),
('First Secondary','Mathematics','Geometry','9','Vectors in the plane','Work with vectors, vector addition and multiplication of a vector by a real number.','https://www.crdp.org/sites/default/files/inline-files/14-Math_2025-2026_.pdf','CRDP curriculum topics 2025–2026',37,'verified')
on conflict do nothing;